language: scala

scala:
  - 2.12.5
jdk:
  - oraclejdk8

sbt_args:
  -no-colors
  -J-Xss2m

env:
  - NODE_VERSION="8.10.0"

before_install:
  - nvm install $NODE_VERSION
  - npm install -g yarn

script:
- sbt ++$TRAVIS_SCALA_VERSION test demo/fastOptJS::webpack
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  yarn: true
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/yarn
